title: Cesar's Ramirez CIT_480 Blog 6

logo: /assets/img/computer.jpg
description: A blog for Technology and tools for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
